In [7]:
#https://github.com/datasciencedojo/datasets
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

# https://github.com/mwaskom/seaborn-data/tree/master

iris_dataset_github_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv"

# kaggle
kaggle_link = "https://www.kaggle.com/datasets/yasserh/titanic-dataset/data"

In [2]:
import pandas as pd

In [8]:
df = pd.read_csv(titanic_dataset_github_url)

In [4]:
df.head()

NameError: name 'df' is not defined

In [5]:
df['Name'].str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [6]:
df.loc[1]['Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [7]:
df['Name'].str.find('Mr')

0       8
1       9
2      -1
3      10
4       7
       ..
886    -1
887    -1
888    -1
889     6
890     8
Name: Name, Length: 891, dtype: int64

In [10]:
count = df['Name'].str.contains('Miss').sum()
print("Number of 'Miss':", count)

Number of 'Miss': 182

In [12]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
     'Email': ['alice@gmail.com', 'bob@gmail.com', 'charlie@gmail.com', 'david@gmail.com']}
df = pd.DataFrame(data)

In [13]:
df.head()

      Name              Email
0    Alice    alice@gmail.com
1      Bob      bob@gmail.com
2  Charlie  charlie@gmail.com
3    David    david@gmail.com

In [14]:
class_data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Groups': ['G1', 'G2', 'G3', 'G4']}

In [16]:
class_df = pd.DataFrame(class_data)

In [17]:
class_df

      Name Groups
0    Alice     G1
1      Bob     G2
2  Charlie     G3
3    David     G4

In [18]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Groups  4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [19]:
class_df['Group_cat'] = pd.Categorical(
   class_df['Groups'],
    categories=['G1', 'G2', 'G3', 'G4'],
    ordered=True 
)

In [20]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       4 non-null      str
 1   Groups     4 non-null      str
 2   Group_cat  4 non-null      category
dtypes: category(1), str(2)
memory usage: 232.0 bytes

In [23]:
df['Embarked'] = df['Embarked'].fillna('N')

In [9]:
df = pd.read_csv(titanic_dataset_github_url)

In [24]:
df['Embarked'].unique()

<StringArray>
['S', 'C', 'Q', 'N']
Length: 4, dtype: str

In [25]:
df['Embarked_autocat'] = df['Embarked'].astype('category')

In [26]:
df['Embarked_cust_cat'] = pd.Categorical(
    df['Embarked'],
    categories=['N', 'S', 'C', 'Q'],
    ordered=True
)

In [27]:
df['Embarked_cust_cat'].cat.categories

Index(['N', 'S', 'C', 'Q'], dtype='str')

In [6]:
import pandas as pd

" Testing"